media: src/_data/media
content:
  - name: homepage
    label: Homepage
    type: file
    format: json
    path: src/_data/posts/home.json
    fields:
      - name: intro
        label: Intro
        type: rich-text
  - name: projects
    label: Projects
    path: src/_data/posts/projects
    type: collection
    fields:
      - name: title
        label: Title
        type: string
      - name: url
        label: URL
        type: string
        pattern: { message: 'This must be a valid URL (e.g. https://example.com).', regex: '^https?:\/\/' }

