media: src/_data/media
content:
  - name: settings
    label: Site Settings
    type: file
    format: json
    path: src/_data/settings.json
    fields:
      - name: colophon
        label: Colophon
        type: rich-text
  - name: homepage
    label: Homepage
    type: file
    format: json
    path: src/index.json
    fields:
      - name: intro
        label: Intro
        type: rich-text
  - name: players
    label: Players
    path: src/_data/players
    type: collection
    format: json
    fields:
      - name: title
        label: Title
        type: string
      - name: url
        label: URL
        type: string
        pattern: { message: 'This must be a valid URL (e.g. https://example.com).', regex: '^https?:\/\/' }


