version: '3.5'
services:
  wordpress:
    build:
      context: .
      args:
        - WORDPRESS_THEME_NAME
    working_dir: /var/www/html/wp-content/themes/${WORDPRESS_THEME_NAME}
    volumes:
      - ./wp/themes/${WORDPRESS_THEME_NAME}:/var/www/html/wp-content/themes/${WORDPRESS_THEME_NAME}
      - ./wp/uploads:/var/www/html/wp-content/uploads
      - ./wp/plugins:/var/www/html/wp-content/plugins
      - ./wp/db:/var/www/html/wp-content/uploads/db-backup
    depends_on:
      - db
    env_file: .env
    networks:
      - proxy
      - default
  db:
    image: mysql:5.7
    volumes:
      - ./docker/initdb.d:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      # See https://hub.docker.com/_/mysql/
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
volumes:
  db_data:
networks:
  proxy:
    name: ups-dock
    external: true
